Repository HIMA-HIMAZIN/webut-memo-app, pull requests merged in 2024-11, with the labels that each got.

#14 メモカードの作成
  public/images/profile_icon/buta.png
  public/images/profile_icon/gorira.png
  public/images/profile_icon/kitune.png
  public/images/profile_icon/panda.png
  public/images/profile_icon/pengin.png
  public/images/profile_icon/raion.png
  src/app/page.tsx
  src/components/buttons/ProfileButton/index.tsx
  src/components/cards/PostingCard/index.tsx
Labels: コンポーネント, スタイル

#15 Feature supabase
  package-lock.json
  package.json
  prisma/migrations/20241105113436_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app/api/memo-log/route.ts
Labels: データベース

#18 Feature fetch memo log data
  src/app/api/memo-log/route.ts
  src/app/page.tsx
  src/components/headers/IconText/index.tsx
  src/types.ts
  src/utils/api.ts
Labels: データベース, 機能

#19 Feature post memo log data
  package-lock.json
  package.json
  src/components/buttons/IosSwitchButton/index.tsx
  src/components/modals/MemoModal/index.tsx
Labels: コンポーネント, 機能

#22 公開設定の投稿のみの表示
  src/app/api/memo-log/route.ts
Labels: 機能

#28 削除・更新の追加
  src/app/api/memo-log/route.ts
  src/utils/api.ts
Labels: 機能

#31 Feature profile page
  package-lock.json
  package.json
  src/app/api/memo-log/route.ts
  src/app/api/profile/route.ts
  src/app/page.tsx
  src/app/pages/individual/page.tsx
  src/components/boxes/ArrowBox/index.tsx
  src/components/boxes/ArrowBox/styles.module.css
  src/components/buttons/ReturnButton/index.tsx
  src/components/cards/IndividualPostingCard/index.tsx
  src/components/cards/PostingCard/index.tsx
  src/components/modals/MemoModal/index.tsx
  src/components/sidebars/LeftSideBar/index.tsx
  src/utils/profile/api.ts
  src/utils/public-all/api.ts
Labels: コンポーネント, 機能, スタイル

#32 プロフィール登録ページ作成
  memo.txt
  src/app/cl_icon/page.tsx
  src/app/cl_name/page.tsx
  src/app/cl_username/page.tsx
  src/components/Bar/ProgressionBer/circle/index.tsx
  src/components/headers/GuideTitle/index.tsx
  src/components/image/image_list/index.tsx
Labels: コンポーネント, スタイル

#34 GoogleによるOAuth認証の成功とポップアップの作成
  src/app/account/page.tsx
  src/app/api/auth.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/modals/AccountModal/index.tsx
  src/components/sidebars/LeftSideBar/index.tsx
Labels: コンポーネント, データベース, 機能

#41 Feature post filter
  .gitignore
  src/app/page.tsx
  src/components/modals/MemoModal/index.tsx
  src/utils/whole/api.ts
Labels: 機能

#45 設定ページとログアウト機能の追加
  src/app/[id]/page.tsx
  src/app/api/signup/handle-name/route.ts
  src/app/page.tsx
  src/app/setting/page.tsx
  src/components/modals/AccountModal/index.tsx
  src/components/modals/SettingsModal/index.tsx
  src/components/sidebars/LeftSideBar/index.tsx
  src/components/sidebars/RightSideBar/index.tsx
  src/utils/supabase/Client.ts
Labels: 機能

#47 Prismaのスキーマを修正しリレーションの値を取得できるように
  prisma/schema.prisma
  src/app/api/memo-log/route.ts
  src/app/api/profile/route.ts
  src/app/page.tsx
  src/components/modals/MemoModal/index.tsx
  src/utils/profile/api.ts
Labels: 機能

#56 他者のプロフィール画面で編集操作が行えないようにする。
  src/app/[id]/page.tsx
Labels: 機能

#57 Feature editor function
  src/app/api/signup/handle-name/route.ts
  src/app/api/signup/user-icon/route.ts
  src/app/api/signup/user-name/route.ts
  src/components/buttons/ProceedButton/index.tsx
  src/components/cards/IndividualPostingCard/index.tsx
  src/components/modals/WarningModal/index.tsx
  src/utils/iconImage/getImageSrcById.ts
  src/utils/signup/api.ts
Labels: 機能

#58 Feature editor function
  src/app/[id]/page.tsx
  src/app/api/individual-memo/route.ts
  src/components/cards/IndividualPostingCard/index.tsx
  src/components/modals/EditModal/index.tsx
  src/components/sidebars/LeftSideBar/index.tsx
  src/utils/IndividualMemo/api.ts
Labels: コンポーネント, 機能, スタイル

#59 Update profile screen
  .gitignore
  src/app/[id]/page.tsx
  src/filters/profanityFilter.ts
Labels: 機能

#60 test用
  .github/workflows/test.yml
Labels: 運用

#67 サインアップ時のユーザー登録
  middleware.ts
  src/app/[id]/page.tsx
  src/app/api/individual-memo/route.ts
  src/app/api/signup/handle-name/route.ts
  src/app/api/signup/user-icon/route.ts
  src/app/api/signup/user-name/route.ts
  src/app/page.tsx
  src/app/signup/display-name/page.tsx
  src/app/signup/select-icon/page.tsx
  src/app/signup/user-name/page.tsx
  src/components/buttons/ProceedButton/index.tsx
  src/components/image/image_list/index.tsx
  src/components/modals/AccountModal/index.tsx
  src/components/modals/MemoModal/index.tsx
  src/components/modals/SettingsModal/index.tsx
  src/components/sidebars/LeftSideBar/index.tsx
  src/hooks/getUser.ts
  src/utils/signup/api.ts
  src/utils/supabase/getCurrentUser.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: データベース, 機能

#74 いいねボタンの追加
  src/components/cards/PostingCard/index.tsx
Labels: スタイル
